name: project_furnitureapp
description: "project_furnitureapp"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  model_viewer_plus: ^1.8.0
  http: ^1.3.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/